# Generated by Django 5.1 on 2024-09-20 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_like_unique_together_biodata_aadhaar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='aadhaar',
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar',
            field=models.CharField(default=123456789012, help_text='Enter your 12-digit Aadhaar number', max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_aadhaar', message='Aadhaar number must be exactly 12 digits', regex='^\\d{12}$')]),
            preserve_default=False,
        ),
    ]
