# Generated by Django 5.1 on 2024-09-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_biodata_about_alter_biodata_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
