# Generated by Django 5.1 on 2024-10-04 04:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_biodata_admin_approval_alter_like_biodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
